### PR TITLE
feat: add meta info (like title) to share intent object on Android

### PR DESCRIPTION
**Pull request by RobinHeidenis**
**Summary**

When sharing a link on Android, the browser adds the page title to the share intent. This is stored in the `Intent.EXTRA_TITLE` property. The library currently has no way of accessing this extra information. This PR adds a `meta` object to the share intent with a `title` property. This way consumers of the library can access the `title` property in their code. On iOS the meta object will be empty.

The code has been set up so it's easily extendible. It will be a small change to add another extra property.

**Todo**

- [x] Update README.md

**Issue**

fixes: #38

### CODE REVIEW

**Review by achorein — COMMENTED** [review]
works well !
just a few little feedbacks

**Comment by RobinHeidenis** [comment]
@achorein I've implemented your changes. Good call on adding to the other example projects, I forgot about that. Anything else we can optimize here?

**Comment by achorein** [comment]
Looks good to me 👍

**Comment by thianphat** [comment]
Would it be possible to add the meta image as well?

**Pull request merged**
